# English (Default)
en:
  languageName: English
  weight: 1 

# Spanish
es:
  languageName: Español
  weight: 2

# French
fr:
  languageName: Français
  weight: 3

# German
de:
  languageName: Deutsch
  weight: 4
