main:
  - name: Contact
    identifier: contact
    weight: 100
    pageRef: /contact/
    params:
      header: Let's connect!
      icon:
        vendor: font-awesome-solid
        name: envelope
  - name: Email
    parent: contact
    url: mailto:Peacefulz@protonmail.com
    weight: 1
    params:
      icon:
        vendor: font-awesome-solid
        name: envelope
        color: "#0072B1"
      description: Send me a message directly.
  - name: Mastodon
    parent: contact
    url: https://infosec.exchange/@Peacefulz
    weight: 2
    params:
      icon:
        vendor: simple
        name: mastodon
        color: "#6364FF"
      description: Follow my updates on Mastodon.
  - name: GitHub
    parent: contact
    url: https://github.com/XoEVOoX
    weight: 3
    params:
      icon:
        vendor: fab
        name: github
        color: "#FFFFFF"
      description: Check out my projects and code.
  - name: YouTube
    parent: contact
    url: https://youtube.com/@PeacefulRS
    weight: 4
    params:
      icon:
        vendor: fab
        name: youtube
        color: "#FF0000"
      description: Watch my videos and tutorials.
  - name: Keybase
    parent: contact
    url: https://keybase.io/Peacefulz
    weight: 5
    params:
      icon:
        vendor: simple
        name: keybase
        color: "#FF0000"
      description: Connect with me securely on Keybase.
