# File: config/_default/module.yaml

# For some regions can not access the proxy.golang.org, i.e. China.
# See https://hugomods.com/en/blog/2023/04/go-and-hugo-proxy-servers/ for all available proxy servers.
# proxy: https://goproxy.cn,direct

# The order of module is very important, precedence from top to bottom.
imports:
  # FIX: Correcting the module path to exclude config files. 
  # We use the root 'meta' module path, not the invalid '/config' subdirectory path.
  - path: github.com/hbstack/meta
    exclude:
      - config/_default/languages.zh-hans.yaml
      - config/_default/menus.zh-hans.yaml
      - config/_default/params.zh-hans.yaml

  # gallery modules.
  - path: github.com/hbstack/gallery
  - path: github.com/hbstack/gallery/modules/breadcrumb

  # syntax highlighting, see https://hbstack.dev/en/docs/modules/syntax-highlighting/.
  # - path: github.com/hbstack/syntax-highlighting/styles/github-dark

  # icons modules
  - path: github.com/hugomods/icons/vendors/font-awesome
  # - path: github.com/hugomods/icons/vendors/mdi
  # - path: github.com/hugomods/icons/vendors/simple-icons
  # - path: github.com/hugomods/icons/vendors/tabler
  # - path: github.com/hugomods/icons/vendors/feather

  # header themes
  # - path: github.com/hbstack/header/themes/pills
  # - path: github.com/hbstack/header/themes/tabs
  # - path: github.com/hbstack/header/themes/classic

  # blog sidebar
  - path: github.com/hbstack/blog/modules/sidebar/profile
  - path: github.com/hbstack/blog/modules/sidebar/posts
  - path: github.com/hbstack/blog/modules/sidebar/taxonomies

  # blog comments engine
  - path: github.com/hbstack/blog/modules/giscus
  # - path: github.com/hbstack/blog/modules/disqus
  # - path: github.com/hbstack/blog/modules/utterances

  # blog table of contents scrollspy
  - path: github.com/hbstack/blog/modules/toc-scrollspy

  # blog content panel
  - path: github.com/hbstack/blog/modules/content-panel

  # docs comments engine
  - path: github.com/hbstack/docs/modules/giscus
  # - path: github.com/hbstack/docs/modules/utterances
  # - path: github.com/hbstack/docs/modules/disqus

  # docs table of contents scrollspy
  - path: github.com/hbstack/docs/modules/toc-scrollspy

  # docs content panel
  - path: github.com/hbstack/docs/modules/content-panel

  # other modules
  # - path: github.com/hugomods/google-analytics
  # - path: github.com/hugomods/google-adsense

  # recommended modules
  # Note: Since 'github.com/hbstack/meta' is imported above, it should load its other resources.
  - path: github.com/hbstack/meta/recommended
